name: expense_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  provider: ^6.1.2
  go_router: ^14.6.2
  http: ^1.3.0
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail_image_network: ^1.2.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  drift_dev: ^2.24.0

flutter:
  uses-material-design: true
