// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct Hello {
  var hello: String? = nil
  var world: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Hello? {
    let hello: String? = nilOrValue(pigeonVar_list[0])
    let world: String? = nilOrValue(pigeonVar_list[1])

    return Hello(
      hello: hello,
      world: world
    )
  }
  func toList() -> [Any?] {
    return [
      hello,
      world,
    ]
  }
}

private class HelloPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return Hello.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HelloPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Hello {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HelloPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HelloPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HelloPigeonPigeonCodecWriter(data: data)
  }
}

class HelloPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HelloPigeonPigeonCodec(readerWriter: HelloPigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HelloPigeon {
  func sayHello() throws -> Hello
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HelloPigeonSetup {
  static var codec: FlutterStandardMessageCodec { HelloPigeonPigeonCodec.shared }
  /// Sets up an instance of `HelloPigeon` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HelloPigeon?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let sayHelloChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.expense_manager.HelloPigeon.sayHello\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sayHelloChannel.setMessageHandler { _, reply in
        do {
          let result = try api.sayHello()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sayHelloChannel.setMessageHandler(nil)
    }
  }
}
